name: CustomSounds
version: '0.1'
main: me.deadybbb.customsounds.CustomSounds
api-version: '1.20'
dependencies:
  server:
    MCKotlin-Paper:
      load: BEFORE
      required: true
    voicechat:
      load: BEFORE
      required: true
      join-classpath: true
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true